### ISSUE TITLE
Add "Pringles" style note for using Rule keyword in Gherkin

### ISSUE THREAD

**Issue by luke-hill** [cucumber/docs#561]
Once you pop you just can't stop.

When using a Rule keyword in Gherkin, you cannot then "un-use" it, i.e. the following is not semantically possible (Nor will it ever likely be).

```
Feature: A
  Background:
    Given whatever
  Rule: One
    # many scenarios
  Rule: Two
    # many scenarios
  Scenario: Standalone Scenario
```

A User should either make the Standalone scenario part of a new Rule and call it `Rule: Other stuff` or alternatively alter the structure of their gherkin document like so

```
Feature: A
  Background:
    Given whatever
  Scenario: Standalone Scenario
  Rule: One
    # many scenarios
  Rule: Two
    # many scenarios
```
